name: PowerPlugins
version: '1.4.7'

author: Andre_601

api-version: '1.13'

main: net.powerplugins.bot.PowerPlugins

commands: 
  powerplugins:
    aliases:
    - powerp
    - pplugins
    description: 'Improved Plugins command to display plugins in a new and interesting order...'
    usage: '/<command> [category [page]|info <plugin>]'